# Generated by Django 5.0.6 on 2024-05-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_question_author'),
    ]

    operations = [
    ]
